#include <functional>
#include <meta>
#include <string>

namespace fsn {
#if defined(__GNUC__) && !defined(__clang__)
namespace meta = std::meta;

namespace details {
consteval std::vector<meta::info> memberFunctions(meta::info obj) {
  constexpr auto ctx = meta::access_context::unchecked();
  auto members = std::define_static_array(meta::members_of(obj, ctx));
  std::vector<meta::info> result;

  for (auto m : members) {
    if (!meta::is_function(m) || meta::is_constructor(m) ||
        meta::is_destructor(m) || meta::is_conversion_function(m) ||
        !meta::has_identifier(m)) {
      continue;
    }
    result.emplace_back(m);
  }
  return result;
}

consteval meta::info findDataMemberByName(meta::info obj,
                                          std::string_view name) {
  constexpr auto ctx = meta::access_context::unchecked();
  for (auto m : meta::nonstatic_data_members_of(obj, ctx)) {
    if (meta::identifier_of(m) == name) {
      return m;
    }
  }
}

consteval meta::info findMemberFunction(meta::info obj, std::string_view name) {
  for (auto m : memberFunctions(obj)) {
    if (meta::identifier_of(m) == name) {
      return m;
    }
  }
}

} // namespace details

/**
 * @brief Generate `vtable` definition for I interface
 *
 * @code
 * struct I {
 *    void foo();
 *    int bar(int z);
 * };
 * @endcode
 *
 * this vtable must be generated
 *
 * @code
 * struct vtable {
 *      std::copyable_function<void()> foo;
 *      std::copyable_function<int(int)> bar;
 * };
 * @endcode
 *
 * Due to reflection of c++26 we can't generate methods, so this struct generate
 * aggregate with `copyable_function`. Due to SOO `copyable_function` in gcc
 * doesn't allocate memory for "small" lambdas.
 *
 * @tparam I - "Interface" like struct/class with methods declaration
 * @return meta descriptor of generated vtable
 */
template <typename I> consteval meta::info makeVtable(meta::info vtable) {
  std::vector<meta::info> resMembers;
  template for (constexpr auto m :
                std::define_static_array(details::memberFunctions(^^I))) {
    static_assert(!meta::has_template_arguments(m),
                  "Template methods in interface aren't supported");

    // clang-format off
        constexpr auto fnMeta = meta::substitute(^^std::copyable_function, {meta::type_of(m)});
        resMembers.emplace_back(meta::data_member_spec(fnMeta, { .name = meta::identifier_of(m), }));
    // clang-format on
  }

  // clang-format off
    return std::meta::define_aggregate(vtable, resMembers);
  // clang-format on
}

/**
 * @brief Initialize vtable for interface `I` with methods of real type `T`.
 *
 * @tparam I - interface
 * @tparam V - vtable for interface generated by makeVtable
 * @tparam T - real type with methods of this interface
 */
template <typename I, typename V, typename T>
constexpr void fillVTable(V &v, [[maybe_unused]] T *p) {
  template for (constexpr auto m :
                std::define_static_array(details::memberFunctions(^^I))) {
    constexpr auto name = meta::identifier_of(m);

    constexpr auto vtableMember = details::findDataMemberByName(^^V, name);

    v.[:vtableMember:] = [p](auto &&...t) {
      constexpr auto realMember = details::findMemberFunction(^^T, name);
      return p->[:realMember:](t...);
    };
  }
}

#endif

} // namespace fsn
