#pragma once

#include <algorithm>
#include <functional>
#include <meta>
#include <string>
#include <string_view>

#include "reflection_utils.hpp"

namespace fsn {

static constexpr size_t MaxLen = 255;

template <size_t N = MaxLen>
struct FnOptionsT {
    static_assert(
        N == MaxLen,
        "Changing N is not allowed because generation of vtable will not find this annotation in annotation list");

    // array of literal type because for annotations reflection api we need constant expression,
    // char* is not a constant expression

    // New name of generated function
    std::array<char, N> name;
};

using FnOptions = FnOptionsT<>;

namespace details {

template <size_t N = MaxLen>
struct FnDescr {
    // Real name of function
    std::array<char, N> realName;
};

// Helper to convert string_view to array at compile time
template <size_t N = MaxLen>
consteval std::array<char, N> toArray(std::string_view sv) {
    std::array<char, N> arr{};
    const auto copy_len = std::min(sv.size(), N - 1);
    std::copy_n(sv.data(), copy_len, arr.data());
    arr[copy_len] = '\0';
    return arr;
}

template <size_t N = MaxLen>
consteval std::string_view toStringView(const std::array<char, N>& arr) {
    return std::string_view(arr.data(), std::char_traits<char>::length(arr.data()));
}

}  // namespace details

#if defined(__GNUC__) && !defined(__clang__)
namespace meta = std::meta;

namespace details {

consteval meta::info makeVtableMember(meta::info m, const FnOptions& opts) {
    auto name = opts.name[0] == '\0' ? meta::identifier_of(m) : std::string_view{opts.name};

    FnDescr<> genDescr{
        .realName = details::toArray(meta::identifier_of(m)),
    };

    // clang-format off
    return meta::data_member_spec(
            meta::substitute(^^std::copyable_function, { meta::type_of(m) }),
            { 
                .name = name, 
                .annotations = { ^^genDescr },
            }
    );
    // clang-format on
}
}  // namespace details

/**
 * @brief Generate `vtable` definition for I interface
 *
 * @code
 * struct I {
 *    void foo();
 *    int bar(int z) const;
 *    // overloading with same name can't be supported in C++26 so we must rename function in generated vtable
 *    [[=FnOptions(.rename = "myBar")]] int bar();
 * };
 * @endcode
 *
 * this vtable must be generated
 *
 * @code
 * struct vtable {
 *      std::copyable_function<void()> foo;
 *      std::copyable_function<int(int) const> bar;
 *      [[=FnDescr(.realName = "bar")]] std::copyable_function<int()> myBar;
 * };
 * @endcode
 *
 * Due to reflection of c++26 we can't generate methods, so this struct generate
 * aggregate with `copyable_function`. Due to SOO `copyable_function` in gcc
 * doesn't allocate memory for "small" lambdas.
 *
 * @tparam I - "Interface" like struct/class with methods declaration
 * @return meta descriptor of generated vtable
 */
template <typename I>
consteval meta::info makeVtable(meta::info vtable) {
    std::vector<meta::info> resMembers;
    template for (constexpr auto m : std::define_static_array(details::memberFunctionsWithBases(^^I))) {
        static_assert(!meta::has_template_arguments(m), "Template methods in interface aren't supported");

        constexpr auto fnOpts = std::define_static_array(meta::annotations_of_with_type(m, ^^FnOptions));
        static_assert(fnOpts.size() <= 1, "Multiple fn options definition can't be supported");

        FnOptions opts = [&fnOpts]() {
            if constexpr (!fnOpts.empty()) {
                constexpr auto constant = meta::constant_of(fnOpts[0]);
                return [:constant:];
            }
            return FnOptions{};
        }();

        resMembers.emplace_back(details::makeVtableMember(m, opts));
    }

    // clang-format off
    return std::meta::define_aggregate(vtable, resMembers);
    // clang-format on
}

template <typename T, typename I, auto Name, auto FnType>
struct InterfaceIncompatibleError {
    static constexpr bool value = false;
};

/**
 * @brief Initialize vtable for interface `I` with methods of real type `T`.
 *
 * @tparam I - interface
 * @tparam V - vtable for interface generated by makeVtable
 * @tparam T - real type with methods of this interface
 */
template <typename I, typename V, typename T>
constexpr void fillVTable(V& v, [[maybe_unused]] T* p) {
    constexpr auto ctx = meta::access_context::unchecked();
    template for (constexpr auto m : std::define_static_array(meta::nonstatic_data_members_of(^^V, ctx))) {
        constexpr auto annotations = std::define_static_array(meta::annotations_of_with_type(m, ^^details::FnDescr<>));
        static_assert(annotations.size() == 1,
                      "Annotations of generated vtable function can't be empty. Is 'V' argument makeVtable result?");

        // actual type of function in interface
        constexpr auto fnType = meta::template_arguments_of(meta::type_of(m))[0];
        constexpr auto opts = [:meta::constant_of(annotations[0]):];
        constexpr auto name = std::define_static_string(details::toStringView(opts.realName));
        constexpr auto pMember = details::findMemberFunction(^^T, name, fnType);

        if constexpr (pMember == ^^details::MemberFunctionError) {
            static_assert(
                InterfaceIncompatibleError<T, I, name,
                                           std::define_static_string(meta::display_string_of(fnType))>::value,
                "InterfaceIncompatibleError<Type, Interface, FunctionName, FunctionType>: your Type doesn't implement "
                "Interface because it does not contain FunctionName with FunctionType as required by the Interface");
        } else {
            v.[:m:] = [p](auto&&... t) noexcept(meta::is_noexcept(fnType)) {
                return p->[:pMember:](std::forward<decltype(t)>(t)...);
            };
        }
    }
}

#endif

}  // namespace fsn
