#pragma once

#include <format>
#include <meta>

namespace fsn::details {
#if defined(__GNUC__) && !defined(__clang__)
namespace meta = std::meta;

/**
 * @brief Get all *non-generated by compiler* methods of `type`
 */
consteval std::vector<meta::info> memberFunctions(meta::info type) {
    constexpr auto ctx = meta::access_context::unchecked();
    auto members = meta::members_of(type, ctx);
    std::vector<meta::info> result;

    for (auto m : members) {
        if (!meta::is_function(m) || meta::is_constructor(m) || meta::is_destructor(m) ||
            meta::is_conversion_function(m) || !meta::has_identifier(m)) {
            continue;
        }
        result.emplace_back(m);
    }
    return result;
}

/**
 * @brief Get all bases (also bases of bases, etc.) of `type`.
 */
consteval std::vector<meta::info> allBases(meta::info type) {
    constexpr auto ctx = meta::access_context::unchecked();

    std::vector<meta::info> result = meta::bases_of(type, ctx);
    std::vector<meta::info> subBase;
    for (auto base : result) {
        subBase.append_range(allBases(meta::type_of(base)));
    }
    result.append_range(subBase);
    return result;
}

/**
 * @brief Get all *non-generated by compiler* methods of `type` and all of its bases classes
 *
 * @param type
 */
consteval std::vector<meta::info> memberFunctionsWithBases(meta::info type) {
    auto bases = allBases(type);

    auto functions = memberFunctions(type);
    for (auto b : bases) {
        functions.append_range(memberFunctions(meta::type_of(b)));
    }

    return functions;
}

/**
 * @class MethodsDuplicationWithDifferentTypesException
 * @brief Exception if method `name` have different types in interface
 *
 */
struct MethodHaveDifferentTypesException {
    std::string_view name;
    meta::info fType;
    meta::info sType;
};

/**
 * @brief Remove all same methods (same name and type) from `types` (it could happened while collecting
 * methods of base classes) to avoid compile error.
 * If this method finds the same name and different type of methods it will emit compile error
 */
consteval std::vector<meta::info> deduplicateMethods(std::vector<meta::info> types) {
    std::vector<meta::info> result;

    for (auto fn : types) {
        bool isDuplicate{};

        for (auto existingFn : result) {
            if (meta::identifier_of(existingFn) != meta::identifier_of(fn)) {
                continue;
            }

            if (meta::type_of(existingFn) == meta::type_of(fn)) {
                isDuplicate = true;
                break;
            } else {
                throw MethodHaveDifferentTypesException{
                    .name = meta::identifier_of(fn),
                    .fType = meta::type_of(existingFn),
                    .sType = meta::type_of(fn),
                };
            }
        }

        if (!isDuplicate) {
            result.emplace_back(fn);
        }
    }

    return result;
}

/**
 * @class MemberFunctionError
 * @brief Special marker of error to generate pretty message about that happened to user
 *
 */
struct MemberFunctionError {};

// Find function in `obj` with `name` and type `fnType`. `fnType` includes const, noexcept etc.
consteval meta::info findMemberFunction(meta::info obj, std::string_view name, [[maybe_unused]] meta::info fnType) {
    for (auto m : memberFunctions(obj)) {
        if (meta::identifier_of(m) == name && meta::type_of(m) == fnType) {
            return m;
        }
    }

    return ^^MemberFunctionError;
}

// Text description of aggregate for debug purposes
template <typename O>
std::string debugAggregate() {
    constexpr auto ctx = meta::access_context::unchecked();
    std::string result;
    template for (constexpr auto m : std::define_static_array(meta::nonstatic_data_members_of(^^O, ctx))) {
        template for (constexpr auto a : std::define_static_array(meta::annotations_of(m))) {
            result += meta::display_string_of(a);
            result += ' ';
        }

        result += meta::display_string_of(meta::type_of(m));
        result += " ";
        result += meta::identifier_of(m);
        result += ";\n";
    }
    return result;
}
#endif
}  // namespace fsn::details
